import type { Config } from 'tailwindcss'

const config: Config = {
  content: ['./src/components/**/*.{js,ts,jsx,tsx}', './src/app/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'selector',
  future: {
    hoverOnlyWhenSupported: true,
  },
  corePlugins: {
    aspectRatio: false,
  },
  plugins: [require('@tailwindcss/aspect-ratio')],
  theme: {
    screens: {
      xs: '480px',
      sm: '640px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
      '2xl': '1536px',
      '3xl': '1920px',
    },
    extend: {
      colors: {
        text: 'rgb(var(--color-dark-950) / <alpha-value>)',
        contrast: 'rgb(var(--color-dark-50) / <alpha-value>)',
        bg: 'rgb(var(--color-dark-50) / <alpha-value>)',
        darkBg: 'rgb(var(--color-dark-800) / <alpha-value>)',
        primary: {
          '50': 'rgb(var(--color-prim-50) / <alpha-value>)',
          '100': 'rgb(var(--color-prim-100) / <alpha-value>)',
          '200': 'rgb(var(--color-prim-200) / <alpha-value>)',
          '300': 'rgb(var(--color-prim-300) / <alpha-value>)',
          '400': 'rgb(var(--color-prim-400) / <alpha-value>)',
          '500': 'rgb(var(--color-prim-500) / <alpha-value>)',
          '600': 'rgb(var(--color-prim-600) / <alpha-value>)',
          '700': 'rgb(var(--color-prim-700) / <alpha-value>)',
          '800': 'rgb(var(--color-prim-800) / <alpha-value>)',
          '900': 'rgb(var(--color-prim-900) / <alpha-value>)',
          '950': 'rgb(var(--color-prim-950) / <alpha-value>)',
        },
        secondary: {
          '50': 'rgb(var(--color-second-50) / <alpha-value>)',
          '100': 'rgb(var(--color-second-100) / <alpha-value>)',
          '200': 'rgb(var(--color-second-200) / <alpha-value>)',
          '300': 'rgb(var(--color-second-300) / <alpha-value>)',
          '400': 'rgb(var(--color-second-400) / <alpha-value>)',
          '500': 'rgb(var(--color-second-500) / <alpha-value>)',
          '600': 'rgb(var(--color-second-600) / <alpha-value>)',
          '700': 'rgb(var(--color-second-700) / <alpha-value>)',
          '800': 'rgb(var(--color-second-800) / <alpha-value>)',
          '900': 'rgb(var(--color-second-900) / <alpha-value>)',
          '950': 'rgb(var(--color-second-950) / <alpha-value>)',
        },
        terciary: {
          '50': 'rgb(var(--color-terc-50) / <alpha-value>)',
          '100': 'rgb(var(--color-terc-100) / <alpha-value>)',
          '200': 'rgb(var(--color-terc-200) / <alpha-value>)',
          '300': 'rgb(var(--color-terc-300) / <alpha-value>)',
          '400': 'rgb(var(--color-terc-400) / <alpha-value>)',
          '500': 'rgb(var(--color-terc-500) / <alpha-value>)',
          '600': 'rgb(var(--color-terc-600) / <alpha-value>)',
          '700': 'rgb(var(--color-terc-700) / <alpha-value>)',
          '800': 'rgb(var(--color-terc-800) / <alpha-value>)',
          '900': 'rgb(var(--color-terc-900) / <alpha-value>)',
          '950': 'rgb(var(--color-terc-950) / <alpha-value>)',
        },
        dark: {
          '50': 'rgb(var(--color-dark-50) / <alpha-value>)',
          '100': 'rgb(var(--color-dark-100) / <alpha-value>)',
          '200': 'rgb(var(--color-dark-200) / <alpha-value>)',
          '300': 'rgb(var(--color-dark-300) / <alpha-value>)',
          '400': 'rgb(var(--color-dark-400) / <alpha-value>)',
          '500': 'rgb(var(--color-dark-500) / <alpha-value>)',
          '600': 'rgb(var(--color-dark-600) / <alpha-value>)',
          '700': 'rgb(var(--color-dark-700) / <alpha-value>)',
          '800': 'rgb(var(--color-dark-800) / <alpha-value>)',
          '900': 'rgb(var(--color-dark-900) / <alpha-value>)',
          '950': 'rgb(var(--color-dark-950) / <alpha-value>)',
        },
        info: {
          '50': 'rgb(var(--color-info-50) / <alpha-value>)',
          '100': 'rgb(var(--color-info-100) / <alpha-value>)',
          '200': 'rgb(var(--color-info-200) / <alpha-value>)',
          '300': 'rgb(var(--color-info-300) / <alpha-value>)',
          '400': 'rgb(var(--color-info-400) / <alpha-value>)',
          '500': 'rgb(var(--color-info-500) / <alpha-value>)',
          '600': 'rgb(var(--color-info-600) / <alpha-value>)',
          '700': 'rgb(var(--color-info-700) / <alpha-value>)',
          '800': 'rgb(var(--color-info-800) / <alpha-value>)',
          '900': 'rgb(var(--color-info-900) / <alpha-value>)',
          '950': 'rgb(var(--color-info-950) / <alpha-value>)',
        },
        success: {
          '50': 'rgb(var(--color-success-50) / <alpha-value>)',
          '100': 'rgb(var(--color-success-100) / <alpha-value>)',
          '200': 'rgb(var(--color-success-200) / <alpha-value>)',
          '300': 'rgb(var(--color-success-300) / <alpha-value>)',
          '400': 'rgb(var(--color-success-400) / <alpha-value>)',
          '500': 'rgb(var(--color-success-500) / <alpha-value>)',
          '600': 'rgb(var(--color-success-600) / <alpha-value>)',
          '700': 'rgb(var(--color-success-700) / <alpha-value>)',
          '800': 'rgb(var(--color-success-800) / <alpha-value>)',
          '900': 'rgb(var(--color-success-900) / <alpha-value>)',
          '950': 'rgb(var(--color-success-950) / <alpha-value>)',
        },
        warning: {
          '50': 'rgb(var(--color-warning-50) / <alpha-value>)',
          '100': 'rgb(var(--color-warning-100) / <alpha-value>)',
          '200': 'rgb(var(--color-warning-200) / <alpha-value>)',
          '300': 'rgb(var(--color-warning-300) / <alpha-value>)',
          '400': 'rgb(var(--color-warning-400) / <alpha-value>)',
          '500': 'rgb(var(--color-warning-500) / <alpha-value>)',
          '600': 'rgb(var(--color-warning-600) / <alpha-value>)',
          '700': 'rgb(var(--color-warning-700) / <alpha-value>)',
          '800': 'rgb(var(--color-warning-800) / <alpha-value>)',
          '900': 'rgb(var(--color-warning-900) / <alpha-value>)',
          '950': 'rgb(var(--color-warning-950) / <alpha-value>)',
        },
        error: {
          '50': 'rgb(var(--color-error-50) / <alpha-value>)',
          '100': 'rgb(var(--color-error-100) / <alpha-value>)',
          '200': 'rgb(var(--color-error-200) / <alpha-value>)',
          '300': 'rgb(var(--color-error-300) / <alpha-value>)',
          '400': 'rgb(var(--color-error-400) / <alpha-value>)',
          '500': 'rgb(var(--color-error-500) / <alpha-value>)',
          '600': 'rgb(var(--color-error-600) / <alpha-value>)',
          '700': 'rgb(var(--color-error-700) / <alpha-value>)',
          '800': 'rgb(var(--color-error-800) / <alpha-value>)',
          '900': 'rgb(var(--color-error-900) / <alpha-value>)',
          '950': 'rgb(var(--color-error-950) / <alpha-value>)',
        },
      },
      spacing: {
        sm: 'theme(fontSize.sm)',
        smPY: '0.375rem',
        smPX: '0.75rem',
        // should be equal to sm text line height
        smIcon: '1.25rem',
        md: 'theme(fontSize.base)',
        mdPY: '0.5rem',
        mdPX: '1rem',
        // should be equal to md text line height
        mdIcon: '1.5rem',
        lg: 'theme(fontSize.lg)',
        lgPY: '0.625rem',
        lgPX: '1.25rem',
        // should be equal to lg text line height
        lgIcon: '1.75rem',
        xl: 'theme(fontSize.xl)',
        xlIcon: '1.75rem',
        '2xl': 'theme(fontSize.2xl)',
        '2xlIcon': '2rem',
        '3xl': 'theme(fontSize.3xl)',
        smHeaderHeight: '3.375rem',
      },
      boxShadow: {
        header: 'var(--shadow-header)',
        button: 'var(--shadow-button)',
        paper: 'var(--shadow-paper)',
        modal: 'var(--shadow-modal)',
        error: 'var(--shadow-error)',
        ring: 'var(--shadow-ring)',
      },
      transitionProperty: {
        colors:
          'color, background-color, border-color, text-decoration-color, fill, stroke, opacity',
        position: 'top, left, bottom, right, transform, opacity',
        activity: 'background-color, color, box-shadow, border-color',
        maxHeight: 'max-height, opacity',
        width: 'width',
        margin: 'margin',
        disableAutofill: 'backgroundColor 600000s 0s, color 600000s 0s',
      },
      animation: {
        ghostAnim: 'ghostAnim 1500ms infinite',
        inlineLoaderAnim: 'inlineLoaderAnim 1400ms infinite',
        circularLoaderAnim:
          'circularLoaderAnim1 800ms infinite linear alternate, circularLoaderAnim2 1600ms infinite linear',
      },
    },
  },
}
export default config
