import type { Config } from 'tailwindcss'

const config: Config = {
  content: ['./src/components/**/*.{js,ts,jsx,tsx}', './src/app/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'selector',
  future: {
    hoverOnlyWhenSupported: true,
  },
  theme: {
    screens: {
      xs: '480px',
      sm: '640px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
      '2xl': '1536px',
      '3xl': '1920px',
    },
    extend: {
      colors: {
        text: 'var(--color-dark-950)',
        darkText: 'var(--color-dark-50)',
        bg: 'var(--color-dark-50)',
        darkBg: 'var(--color-dark-800)',
        overlay: '#00000033',
        primary: {
          '50': 'var(--color-prim-50)',
          '100': 'var(--color-prim-100)',
          '200': 'var(--color-prim-200)',
          '300': 'var(--color-prim-300)',
          '400': 'var(--color-prim-400)',
          '500': 'var(--color-prim-500)',
          '600': 'var(--color-prim-600)',
          '700': 'var(--color-prim-700)',
          '800': 'var(--color-prim-800)',
          '900': 'var(--color-prim-900)',
          '950': 'var(--color-prim-950)',
        },
        secondary: {
          '50': 'var(--color-second-50)',
          '100': 'var(--color-second-100)',
          '200': 'var(--color-second-200)',
          '300': 'var(--color-second-300)',
          '400': 'var(--color-second-400)',
          '500': 'var(--color-second-500)',
          '600': 'var(--color-second-600)',
          '700': 'var(--color-second-700)',
          '800': 'var(--color-second-800)',
          '900': 'var(--color-second-900)',
          '950': 'var(--color-second-950)',
        },
        terciary: {
          '50': 'var(--color-terc-50)',
          '100': 'var(--color-terc-100)',
          '200': 'var(--color-terc-200)',
          '300': 'var(--color-terc-300)',
          '400': 'var(--color-terc-400)',
          '500': 'var(--color-terc-500)',
          '600': 'var(--color-terc-600)',
          '700': 'var(--color-terc-700)',
          '800': 'var(--color-terc-800)',
          '900': 'var(--color-terc-900)',
          '950': 'var(--color-terc-950)',
        },
        dark: {
          '50': 'var(--color-dark-50)',
          '100': 'var(--color-dark-100)',
          '200': 'var(--color-dark-200)',
          '300': 'var(--color-dark-300)',
          '400': 'var(--color-dark-400)',
          '500': 'var(--color-dark-500)',
          '600': 'var(--color-dark-600)',
          '700': 'var(--color-dark-700)',
          '800': 'var(--color-dark-800)',
          '900': 'var(--color-dark-900)',
          '950': 'var(--color-dark-950)',
        },
        info: {
          '50': 'var(--color-info-50)',
          '100': 'var(--color-info-100)',
          '200': 'var(--color-info-200)',
          '300': 'var(--color-info-300)',
          '400': 'var(--color-info-400)',
          '500': 'var(--color-info-500)',
          '600': 'var(--color-info-600)',
          '700': 'var(--color-info-700)',
          '800': 'var(--color-info-800)',
          '900': 'var(--color-info-900)',
          '950': 'var(--color-info-950)',
        },
        success: {
          '50': 'var(--color-success-50)',
          '100': 'var(--color-success-100)',
          '200': 'var(--color-success-200)',
          '300': 'var(--color-success-300)',
          '400': 'var(--color-success-400)',
          '500': 'var(--color-success-500)',
          '600': 'var(--color-success-600)',
          '700': 'var(--color-success-700)',
          '800': 'var(--color-success-800)',
          '900': 'var(--color-success-900)',
          '950': 'var(--color-success-950)',
        },
        warning: {
          '50': 'var(--color-warning-50)',
          '100': 'var(--color-warning-100)',
          '200': 'var(--color-warning-200)',
          '300': 'var(--color-warning-300)',
          '400': 'var(--color-warning-400)',
          '500': 'var(--color-warning-500)',
          '600': 'var(--color-warning-600)',
          '700': 'var(--color-warning-700)',
          '800': 'var(--color-warning-800)',
          '900': 'var(--color-warning-900)',
          '950': 'var(--color-warning-950)',
        },
        error: {
          '50': 'var(--color-error-50)',
          '100': 'var(--color-error-100)',
          '200': 'var(--color-error-200)',
          '300': 'var(--color-error-300)',
          '400': 'var(--color-error-400)',
          '500': 'var(--color-error-500)',
          '600': 'var(--color-error-600)',
          '700': 'var(--color-error-700)',
          '800': 'var(--color-error-800)',
          '900': 'var(--color-error-900)',
          '950': 'var(--color-error-950)',
        },
      },
      spacing: {
        sm: 'theme(fontSize.sm)',
        smPY: '0.375rem',
        smPX: '0.75rem',
        // should be equal to sm text line height
        smIcon: '1.25rem',
        md: 'theme(fontSize.base)',
        mdPY: '0.5rem',
        mdPX: '1rem',
        // should be equal to md text line height
        mdIcon: '1.5rem',
        lg: 'theme(fontSize.lg)',
        lgPY: '0.625rem',
        lgPX: '1.25rem',
        // should be equal to lg text line height
        lgIcon: '1.75rem',
        xl: 'theme(fontSize.xl)',
        xlIcon: '1.75rem',
        '2xl': 'theme(fontSize.2xl)',
        '2xlIcon': '2rem',
        '3xl': 'theme(fontSize.3xl)',
        smHeaderHeight: '3.375rem',
      },
      boxShadow: {
        header: 'var(--shadow-header)',
        button: 'var(--shadow-button)',
        paper: 'var(--shadow-paper)',
        modal: 'var(--shadow-modal)',
        error: 'var(--shadow-error)',
      },
      transitionProperty: {
        colors:
          'color, background-color, border-color, text-decoration-color, fill, stroke, opacity',
        dropdown: 'top, left, bottom, right, transform, opacity',
        activity: 'background-color, color, box-shadow, border-color',
        maxHeight: 'max-height',
        width: 'width',
        margin: 'margin',
        disableAutofill: 'backgroundColor 600000s 0s, color 600000s 0s',
      },
      animation: {
        ghostAnim: 'ghostAnim 1500ms infinite',
        inlineLoaderAnim: 'inlineLoaderAnim 1400ms infinite',
        circularLoaderAnim:
          'circularLoaderAnim1 800ms infinite linear alternate, circularLoaderAnim2 1600ms infinite linear',
      },
    },
  },
  plugins: [],
}
export default config
