import {
  baseVariant,
  errorStateClass,
  focusVisibleVariant,
  iconPaddingSize,
  interactiveVariant,
  paddingSize,
  textSize,
  textVariant,
} from '@/components/utils/common.style'
import { cn } from '@/utils/utils'

export const buttonClass = cn(
  'relative cursor-pointer items-center justify-center gap-2 rounded-md border font-semibold whitespace-nowrap transition-colors focus:outline-hidden focus-visible:z-10 focus-visible:ring-1',
  errorStateClass,
)

export const buttonVariant = {
  text: {
    primary: cn(
      baseVariant.text.primary,
      textVariant.text.primary,
      'bg-transparent dark:bg-transparent',
      focusVisibleVariant.text.primary,
      interactiveVariant.text.primary,
    ),
    secondary: cn(
      baseVariant.text.secondary,
      textVariant.text.secondary,
      'bg-transparent dark:bg-transparent',
      focusVisibleVariant.text.secondary,
      interactiveVariant.text.secondary,
    ),
    terciary: cn(
      baseVariant.text.terciary,
      textVariant.text.terciary,
      'bg-transparent dark:bg-transparent',
      focusVisibleVariant.text.terciary,
      interactiveVariant.text.terciary,
    ),
    error: cn(
      'text-error-800 dark:text-error-100 border-transparent bg-transparent dark:bg-transparent',
      'focus-visible:bg-error-100 focus-visible:ring-error-800',
      'dark:focus-visible:bg-error-100/10 dark:focus-visible:ring-error-100',
      'group-focus-visible:bg-error-100 dark:group-focus-visible:bg-error-100/10',
      '[&[data-selected]]:focus-visible:bg-error-200 dark:[&[data-selected]]:focus-visible:bg-error-100/25',
      'hoverable:bg-error-100 dark:hoverable:bg-error-100/10',
      'active:bg-error-200 dark:active:bg-error-100/20',
      '[&[data-selected]]:bg-error-100 dark:[&[data-selected]]:bg-error-100/15',
      'hoverable:[&[data-selected]]:bg-error-200 dark:hoverable:[&[data-selected]]:bg-error-100/25',
      '[&[data-selected]]:active:bg-error-300 dark:[&[data-selected]]:active:bg-error-100/30',
    ),
    success: cn(
      'text-success-800 dark:text-success-100 border-transparent bg-transparent dark:bg-transparent',
      'focus-visible:bg-success-100 focus-visible:ring-success-800',
      'dark:focus-visible:bg-success-100/10 dark:focus-visible:ring-success-100',
      'group-focus-visible:bg-success-100 dark:group-focus-visible:bg-success-100/10',
      '[&[data-selected]]:focus-visible:bg-success-200 dark:[&[data-selected]]:focus-visible:bg-success-100/25',
      'hoverable:bg-success-100 dark:hoverable:bg-success-100/10',
      'active:bg-success-200 dark:active:bg-success-100/20',
      '[&[data-selected]]:bg-success-100 dark:[&[data-selected]]:bg-success-100/15',
      'hoverable:[&[data-selected]]:bg-success-200 dark:hoverable:[&[data-selected]]:bg-success-100/25',
      '[&[data-selected]]:active:bg-success-300 dark:[&[data-selected]]:active:bg-success-100/30',
    ),
    ghost: cn(
      'text-dark-300 border-transparent bg-transparent',
      'focus-visible:bg-dark-950/50 focus-visible:ring-dark-300 focus-visible:text-contrast',
      'group-focus-visible:bg-dark-950/50',
      '[&[data-selected]]:focus-visible:bg-dark-950/70',
      'hoverable:bg-dark-950/50 hoverable:text-contrast',
      'active:bg-dark-950/70 active:text-contrast',
      '[&[data-selected]]:text-contrast',
      'hoverable:[&[data-selected]]:bg-dark-950/50',
      '[&[data-selected]]:active:bg-dark-950/70',
    ),
    none: '',
  },
  outlined: {
    primary: cn(
      baseVariant.outlined.primary,
      textVariant.outlined.primary,
      'bg-transparent dark:bg-transparent',
      focusVisibleVariant.outlined.primary,
      interactiveVariant.outlined.primary,
    ),
    secondary: cn(
      baseVariant.outlined.secondary,
      textVariant.outlined.secondary,
      'bg-transparent dark:bg-transparent',
      focusVisibleVariant.outlined.secondary,
      interactiveVariant.outlined.secondary,
    ),
    terciary: cn(
      baseVariant.outlined.terciary,
      textVariant.outlined.terciary,
      'bg-transparent dark:bg-transparent',
      focusVisibleVariant.outlined.terciary,
      interactiveVariant.outlined.terciary,
    ),
    error: cn(
      'border-error-800 dark:border-error-100 text-error-800 dark:text-error-100 bg-transparent dark:bg-transparent',
      'focus-visible:bg-error-100 focus-visible:ring-error-800',
      'dark:focus-visible:bg-error-100/10 dark:focus-visible:ring-error-100',
      'group-focus-visible:bg-error-100 dark:group-focus-visible:bg-error-100/10',
      '[&[data-selected]]:focus-visible:bg-error-200 dark:[&[data-selected]]:focus-visible:bg-error-100/25',
      'hoverable:bg-error-100 dark:hoverable:bg-error-100/10',
      'active:bg-error-200 dark:active:bg-error-100/20',
      '[&[data-selected]]:bg-error-100 dark:[&[data-selected]]:bg-error-100/15',
      'hoverable:[&[data-selected]]:bg-error-200 dark:hoverable:[&[data-selected]]:bg-error-100/25',
      '[&[data-selected]]:active:bg-error-300 dark:[&[data-selected]]:active:bg-error-100/30',
    ),
    success: cn(
      'border-success-800 dark:border-success-100 text-success-800 dark:text-success-100 bg-transparent dark:bg-transparent',
      'focus-visible:bg-success-100 focus-visible:ring-success-800',
      'dark:focus-visible:bg-success-100/10 dark:focus-visible:ring-success-100',
      'group-focus-visible:bg-success-100 dark:group-focus-visible:bg-success-100/10',
      '[&[data-selected]]:focus-visible:bg-success-200 dark:[&[data-selected]]:focus-visible:bg-success-100/25',
      'hoverable:bg-success-100 dark:hoverable:bg-success-100/10',
      'active:bg-success-200 dark:active:bg-success-100/20',
      '[&[data-selected]]:bg-success-100 dark:[&[data-selected]]:bg-success-100/15',
      'hoverable:[&[data-selected]]:bg-success-200 dark:hoverable:[&[data-selected]]:bg-success-100/25',
      '[&[data-selected]]:active:bg-success-300 dark:[&[data-selected]]:active:bg-success-100/30',
    ),
    ghost: cn(
      'border-dark-300 text-dark-300 bg-transparent',
      'focus-visible:bg-dark-950/50 focus-visible:ring-dark-300 focus-visible:text-contrast',
      'group-focus-visible:bg-dark-950/50',
      '[&[data-selected]]:focus-visible:bg-dark-950/70',
      'hoverable:bg-dark-950/50 hoverable:text-contrast',
      'active:bg-dark-950/70 active:text-contrast',
      '[&[data-selected]]:text-contrast',
      'hoverable:[&[data-selected]]:bg-dark-950/50',
      '[&[data-selected]]:active:bg-dark-950/70',
    ),
    none: '',
  },
  contained: {
    primary: cn(
      baseVariant.contained.primary,
      focusVisibleVariant.contained.primary,
      interactiveVariant.contained.primary,
    ),
    secondary: cn(
      baseVariant.contained.secondary,
      focusVisibleVariant.contained.secondary,
      interactiveVariant.contained.secondary,
    ),
    terciary: cn(
      baseVariant.contained.terciary,
      focusVisibleVariant.contained.terciary,
      interactiveVariant.contained.terciary,
    ),
    error: cn(
      'border-error-800 bg-error-700 from-error-700 text-error-50',
      'focus-visible:bg-error-600 focus-visible:ring-error-900',
      'group-focus-visible:bg-error-600',
      '[&[data-selected]]:focus-visible:bg-error-500',
      'hoverable:bg-error-600 active:bg-error-500',
      '[&[data-selected]]:bg-error-600 hoverable:[&[data-selected]]:bg-error-500 [&[data-selected]]:active:bg-error-500',
    ),
    success: cn(
      'border-success-800 bg-success-700 from-success-700 text-success-50',
      'focus-visible:bg-success-600 focus-visible:ring-success-900',
      'group-focus-visible:bg-success-600',
      '[&[data-selected]]:focus-visible:bg-success-500',
      'hoverable:bg-success-600 active:bg-success-500',
      '[&[data-selected]]:bg-success-600 hoverable:[&[data-selected]]:bg-success-500 [&[data-selected]]:active:bg-success-500',
    ),
    ghost: cn(
      'bg-dark-950/25 text-dark-300 border-transparent',
      'focus-visible:bg-dark-950/50 focus-visible:ring-dark-300 focus-visible:text-contrast',
      'group-focus-visible:bg-dark-950/50',
      '[&[data-selected]]:focus-visible:bg-dark-950/70',
      'hoverable:bg-dark-950/50 hoverable:text-contrast',
      'active:bg-dark-950/70 active:text-contrast',
      '[&[data-selected]]:bg-dark-950/50 [&[data-selected]]:text-contrast',
      'hoverable:[&[data-selected]]:bg-dark-950/70',
      '[&[data-selected]]:active:bg-dark-950/80',
    ),
    none: '',
  },
}

export const iconOnlySize = {
  sm: cn(iconPaddingSize.sm, textSize.sm),
  md: cn(iconPaddingSize.md, textSize.md),
  lg: cn(iconPaddingSize.lg, textSize.lg),
  inline: cn('border-0 px-1'),
  none: '',
}

export const buttonSize = {
  sm: cn(paddingSize.sm, textSize.sm),
  md: cn(paddingSize.md, textSize.md),
  lg: cn(paddingSize.lg, textSize.lg),
  inline: cn('border-0 px-1 hover:underline focus-visible:underline'),
  none: '',
}
